pipeline:
  build:
    image: ruby
    commands:
      - gem install bundle
      - bundle install --without=vagrant
      - bundle exec kitchen create ${SUITE} -l warn -c 6
      - bundle exec kitchen converge ${SUITE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  verify:
    image: python
    commands:
      - pip install -r test-requirements.txt
      - bundle exec kitchen verify ${SUITE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
matrix:
  SUITE:
    - bootstrap
    - apt
    - yum
