pipeline:
  build:
    image: alpine
    commands:
      - env
      - apk --update add docker git ruby-bundler ruby-rdoc ruby-dev gcc ruby-dev make libc-dev
      - bundle install --with=docker
      - bundle exec kitchen create ${SUITE} -l warn -c 6
      - bundle exec kitchen converge ${SUITE}
  verify:
    image: alpine
    commands:
      - apk --update add docker python3
      - python3 -m pip install -r test-requirements.txt
      - bundle exec kitchen verify ${SUITE}
matrix:
  SUITE:
    - bootstrap
    - apt
    - yum
