pipeline:
  build:
    image: alpine
    commands:
      - apk update && apk add ruby docker
      - gem install bundler
      - bundle install --without=vagrant
      - bundle exec kitchen create ${SUITE} -l warn -c 6
      - bundle exec kitchen converge ${SUITE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  verify:
    image: alpine
    commands:
      - apk update && apk add python3 docker
      - python3 -m pip install -r test-requirements.txt
      - bundle exec kitchen verify ${SUITE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
matrix:
  SUITE:
    - bootstrap
    - apt
    - yum
