language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - git
    - shellcheck
    - python-pip

rvm:
  - ruby

env:
  matrix:
    - SUITE=apt
    - SUITE=yum
    - SUITE=bootstrap

sudo: true
dist: trusty
bundler_args: --with=docker --without vagrant windows

before_install:
  - pip install -r test-requirements.txt

script:
  # Check shell scripts
  - shellcheck lib/kitchen/provisioner/*.sh*
  - bundle exec gem list
  - cat .kitchen.yml
  # Setup for tests
  - bundle exec kitchen create $SUITE -l warn -c 6
  # Run test-kitchen with docker driver:
  - bundle exec kitchen verify $SUITE

after_script:
  - bundle exec kitchen list
  - bundle exec kitchen destroy all
