language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - subversion
    - git
    - shellcheck
    - tree

rvm:
  - 2.2.4
  - ruby
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: true
dist: trusty

bundler_args: --without='vagrant'

install:
  - bundle install --without='vagrant'
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen list

script:
  # Run unit tests
  - bundle exec rspec
  # Check shell scripts
  - shellcheck lib/kitchen/provisioner/*.sh*
  # Run test-kitchen with docker driver:
  - bundle exec kitchen test client-single -ldebug

after_failure:
  - tail -c +0 .kitchen/logs/client-single-*.log

after_script:
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen list
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen destroy all
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen diagnose --all
